### ISSUE TITLE
Upgrade from Kyma to eventing-manager with EventMesh backend re-creates the subscriptions on EventMesh server

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/eventing-manager#125] opened 2023-09-29 14:56 UTC
Upgrade from Kyma to eventing-manager with EventMesh backend re-creates the subscriptions on EventMesh server.

**Comment by marcobebway** [comment] 2023-10-12 07:17
Findings

- Upgrading Kyma 2.0 (EventMesh) to Eventing manager (EventMesh) recreates the EventMesh subscriptions.
- Kyma Subscriptions before the upgrade has a different hashes after the upgrade.
- The root cause of this diff in hashing is the different domain configurations [here](https://github.com/kyma-project/kyma/blob/50b5b290622b30a9a7cd1bbf202c06e2e051793c/resources/eventing/charts/controller/templates/deployment.yaml#L33-L36) vs [here](https://github.com/kyma-project/eventing-manager/blob/7b9d669a376eea1555217e28b1230003a5da33ed/config/manager/manager.yaml#L80-L83).

This issue will be fixed [here](https://github.com/kyma-project/eventing-manager/issues/137).

**Closed** 2023-10-20 09:25 UTC
Labels: area/eventing
